const recipes = [
    { name: `Bharela Marcha (Gujarati-Veg)`, category: "Gujarati-Veg", file: "./IN/GUJARATI/bharela-marcha.html" },
    { name: "Bharela Ringan (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/bharela-ringan.html" },
    { name: "Chhundo (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/chhundo.html" },
    { name: "Dal Dhokli (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/dal-dhokli.html" },
    { name: "Dhokla (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/dhokla.html" },
    { name: "Fafda (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/fafda.html" },
    { name: "Ganthiya (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/ganthiya.html" },
    { name: "Ghari (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/ghari.html" },
    { name: "Athanu (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/athanu.html" },
    { name: "Basundi (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/basundi.html" },
    { name: "Handvo (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/handvo.html" },
    { name: "Jalebi (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/jalebi.html" },
    { name: "Kadhi (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/kadhi.html" },
    { name: "Khandvi (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/khandvi.html" },
    { name: "Khichdi (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/khichdi.html" },
    { name: "Kobi Batata (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/kobi-batata.html" },
    { name: "Lasan Chutney (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/lasan-chutney.html" },
    { name: "Limbu Athanu (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/limbu-athanu.html" },
    { name: "Marcha Sambharo (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/marcha-sambharo.html" },
    { name: "Mohanthal (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/mohanthal.html" },
    { name: "Patra (Paratha) (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/paratha.html" },
    { name: "Pulav (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/pulav.html" },
    { name: "Puran Poli (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/puran-poli.html" },
    { name: "Sev (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/sev.html" },
    { name: "Sev Tameta (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/sev-tameta.html" },
    { name: "Shrikhand (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/shrikhand.html" },
    { name: "Sukhdi (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/sukhdi.html" },
    { name: "Turiya Patra (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/turiya-patra.html" },
    { name: "Undhiyu (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/undhiyu.html" },
    { name: "Vagharelo Bhaat (Gujarati-Veg)", category: "Gujarati-Veg", file: "./IN/GUJARATI/vagharelo-bhaat.html" },
    // 
    // Bengali Recipes (Veg & Non-Veg)
    { name: "Aloo Chop (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/aloo-chop.html" },
    { name: "Aloo Posto (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/aloo-posto.html" },
    { name: "Basanti Pulao (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/basanti-pulao.html" },
    { name: "Begun Bharta (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/begun-bharta.html" },
    { name: "Beguni (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/beguni.html" },
    { name: "Bhoger Khichuri (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/bhoger-khichuri.html" },
    { name: "Cham Cham (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/cham-cham.html" },
    { name: "Chana’r Dalna (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/chanar-dalna.html" },
    { name: "Chingri Malai Curry (Bengali-NonVeg)", category: "Bengali-NonVeg", file: "./IN/BENGALI/chingri-malai-curry.html" },
    { name: "Cholar Dal (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/cholar-dal.html" },
    { name: "Chorchori (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/chorchori.html" },
    { name: "Dhokar Dalna (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/dhokar-dalna.html" },
    { name: "Doi Maach (Bengali-NonVeg)", category: "Bengali-NonVeg", file: "./IN/BENGALI/doi-maach.html" },
    { name: "Ghugni (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/ghugni.html" },
    { name: "Kacha Golla (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/kacha-golla.html" },
    { name: "Kosha Mangsho (Bengali-NonVeg)", category: "Bengali-NonVeg", file: "./IN/BENGALI/kosha-mangsho.html" },
    { name: "Labra (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/labra.html" },
    { name: "Lau Chingri (Bengali-NonVeg)", category: "Bengali-NonVeg", file: "./IN/BENGALI/lau-chingri.html" },
    { name: "Macher Jhol (Bengali-NonVeg)", category: "Bengali-NonVeg", file: "./IN/BENGALI/macher-jhol.html" },
    { name: "Masoor Dal (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/masoor-dal.html" },
    { name: "Mishti Doi (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/mishti-doi.html" },
    { name: "Moong Dal (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/moong-dal.html" },
    { name: "Nolen Gurer Payesh (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/nolen-gurer-payesh.html" },
    { name: "Pabda Shorshe (Bengali-NonVeg)", category: "Bengali-NonVeg", file: "./IN/BENGALI/pabda-shorshe.html" },
    { name: "Pantua (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/pantua.html" },
    { name: "Pati Shapta (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/pati-shapta.html" },
    { name: "Plain Steamed Rice (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/plain-steamed-rice.html" },
    { name: "Rasgulla (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/rasgulla.html" },
    { name: "Sandesh (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/sandesh.html" },
    { name: "Shingara (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/shingara.html" },
    { name: "Shorshe Ilish (Bengali-NonVeg)", category: "Bengali-NonVeg", file: "./IN/BENGALI/shorshe-ilish.html" },
    { name: "Shukto (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/shukto.html" },
    { name: "Shutki Machh (Bengali-NonVeg)", category: "Bengali-NonVeg", file: "./IN/BENGALI/shutki-machh.html" },
    { name: "Telebhaja (Bengali-Veg)", category: "Bengali-Veg", file: "./IN/BENGALI/telebhaja.html" },
    // haydrabadi
    { name: "Aloo Kurma (Hyderabadi-Veg)", category: "Hyderabadi-Veg", file: "./IN/HYDERABADI/aloo-kurma.html" },
    { name: "Bagara Baingan (Hyderabadi-Veg)", category: "Hyderabadi-Veg", file: "./IN/HYDERABADI/bagara-baingan.html" },
    { name: "Bagara Baingan with Mutton Curry (Hyderabadi-NonVeg)", category: "Hyderabadi-NonVeg", file: "./IN/HYDERABADI/baghara-baingan-mutton.html" },
    { name: "Bagara Khana (Hyderabadi-Veg)", category: "Hyderabadi-Veg", file: "./IN/HYDERABADI/bagara-khana.html" },
    { name: "Double Ka Meetha (Hyderabadi-Sweet)", category: "Hyderabadi-Sweet", file: "./IN/HYDERABADI/double-ka-meetha.html" },
    { name: "Dum Ka Murgh (Hyderabadi-NonVeg)", category: "Hyderabadi-NonVeg", file: "./IN/HYDERABADI/dum-ka-murgh.html" },
    { name: "Falooda (Hyderabadi-Sweet)", category: "Hyderabadi-Sweet", file: "./IN/HYDERABADI/falooda.html" },
    { name: "Haleem (Hyderabadi-NonVeg)", category: "Hyderabadi-NonVeg", file: "./IN/HYDERABADI/haleem.html" },
    { name: "Hyderabadi Biryani (Hyderabadi-NonVeg)", category: "Hyderabadi-NonVeg", file: "./IN/HYDERABADI/hyderabadi-biryani.html" },
    { name: "Irani Chai (Hyderabadi-Beverage)", category: "Hyderabadi-Beverage", file: "./IN/HYDERABADI/irani-chai.html" },
    { name: "Kacchi Biryani (Hyderabadi-NonVeg)", category: "Hyderabadi-NonVeg", file: "./IN/HYDERABADI/kacchi-biryani.html" },
    { name: "Kaddu Ka Dalcha (Hyderabadi-Veg)", category: "Hyderabadi-Veg", file: "./IN/HYDERABADI/kaddu-ka-dalcha.html" },
    { name: "Keema Samosa (Hyderabadi-NonVeg)", category: "Hyderabadi-NonVeg", file: "./IN/HYDERABADI/keema-samosa.html" },
    { name: "Khatti Dal (Hyderabadi-Veg)", category: "Hyderabadi-Veg", file: "./IN/HYDERABADI/khatti-dal.html" },
    { name: "Khubani Ka Meetha (Hyderabadi-Sweet)", category: "Hyderabadi-Sweet", file: "./IN/HYDERABADI/khubani-ka-meetha.html" },
    { name: "Mirchi Ka Salan (Hyderabadi-Veg)", category: "Hyderabadi-Veg", file: "./IN/HYDERABADI/mirchi-ka-salan.html" },
    { name: "Osmania Biscuits (Hyderabadi-Sweet)", category: "Hyderabadi-Sweet", file: "./IN/HYDERABADI/osmania-biscuits.html" },
    { name: "Pathar Ka Gosht (Hyderabadi-NonVeg)", category: "Hyderabadi-NonVeg", file: "./IN/HYDERABADI/pathar-ka-gosht.html" },
    { name: "Qubani Ka Meetha (Hyderabadi-Sweet)", category: "Hyderabadi-Sweet", file: "./IN/HYDERABADI/qubani-ka-meetha.html" },
    { name: "Shahi Tukda (Hyderabadi-Sweet)", category: "Hyderabadi-Sweet", file: "./IN/HYDERABADI/shahi-tukda.html" },
    { name: "Sheek Kebabs (Hyderabadi-NonVeg)", category: "Hyderabadi-NonVeg", file: "./IN/HYDERABADI/sheek-kebabs.html" },
    { name: "Shikampuri Kebabs (Hyderabadi-NonVeg)", category: "Hyderabadi-NonVeg", file: "./IN/HYDERABADI/shikampuri-kebabs.html" },
    { name: "Talawa Gosht (Hyderabadi-NonVeg)", category: "Hyderabadi-NonVeg", file: "./IN/HYDERABADI/talawa-gosht.html" },
    { name: "Tamate Ka Kut (Hyderabadi-Veg)", category: "Hyderabadi-Veg", file: "./IN/HYDERABADI/tamate-ka-kut.html" },
    // add maharsatian
    // Maharashtrian Recipes (Veg, Non-Veg, Sweets & Snacks)
    { name: "Anarsa (Maharashtrian-Sweet)", category: "Maharashtrian-Sweet", file: "./IN/MAHARASTRIAN/anarsa.html" },
    { name: "Batata Bhaji (Maharashtrian-Veg)", category: "Maharashtrian-Veg", file: "./IN/MAHARASTRIAN/batata-bhaji.html" },
    { name: "Bhakarwadi (Maharashtrian-Snack)", category: "Maharashtrian-Snack", file: "./IN/MAHARASTRIAN/bhakarwadi.html" },
    { name: "Bharli Vangi (Maharashtrian-Veg)", category: "Maharashtrian-Veg", file: "./IN/MAHARASTRIAN/bharli-vangi.html" },
    { name: "Bombil Fry (Maharashtrian-NonVeg)", category: "Maharashtrian-NonVeg", file: "./IN/MAHARASTRIAN/bombil-fry.html" },
    { name: "Chakli (Maharashtrian-Snack)", category: "Maharashtrian-Snack", file: "./IN/MAHARASTRIAN/chakli.html" },
    { name: "Chicken Malvani (Maharashtrian-NonVeg)", category: "Maharashtrian-NonVeg", file: "./IN/MAHARASTRIAN/chicken-malvani.html" },
    { name: "Chicken Rassa (Maharashtrian-NonVeg)", category: "Maharashtrian-NonVeg", file: "./IN/MAHARASTRIAN/chicken-rassa.html" },
    { name: "Egg Curry (Maharashtrian-NonVeg)", category: "Maharashtrian-NonVeg", file: "./IN/MAHARASTRIAN/egg-curry.html" },
    { name: "Gulachi Poli (Maharashtrian-Sweet)", category: "Maharashtrian-Sweet", file: "./IN/MAHARASTRIAN/gulachi-poli.html" },
    { name: "Kanda Bhaji (Maharashtrian-Snack)", category: "Maharashtrian-Snack", file: "./IN/MAHARASTRIAN/kanda-bhaji.html" },
    { name: "Kharvas (Maharashtrian-Sweet)", category: "Maharashtrian-Sweet", file: "./IN/MAHARASTRIAN/kharvas.html" },
    { name: "Kolambi Bhaat (Maharashtrian-NonVeg)", category: "Maharashtrian-NonVeg", file: "./IN/MAHARASTRIAN/kolambi-bhaat.html" },
    { name: "Misal Pav (Maharashtrian-Veg)", category: "Maharashtrian-Veg", file: "./IN/MAHARASTRIAN/misal-pav.html" },
    { name: "Modak (Maharashtrian-Sweet)", category: "Maharashtrian-Sweet", file: "./IN/MAHARASTRIAN/modak.html" },
    { name: "Mutton Sukka (Maharashtrian-NonVeg)", category: "Maharashtrian-NonVeg", file: "./IN/MAHARASTRIAN/mutton-sukka.html" },
    { name: "Pandhra Rassa (Maharashtrian-NonVeg)", category: "Maharashtrian-NonVeg", file: "./IN/MAHARASTRIAN/pandhra-rassa.html" },
    { name: "Poha (Maharashtrian-Veg)", category: "Maharashtrian-Veg", file: "./IN/MAHARASTRIAN/poha.html" },
    { name: "Puran Poli (Maharashtrian-Sweet)", category: "Maharashtrian-Sweet", file: "./IN/MAHARASTRIAN/puran-poli.html" },
    { name: "Sabudana Khichdi (Maharashtrian-Veg)", category: "Maharashtrian-Veg", file: "./IN/MAHARASTRIAN/sabudana-khichdi.html" },
    { name: "Sheera (Maharashtrian-Sweet)", category: "Maharashtrian-Sweet", file: "./IN/MAHARASTRIAN/sheera.html" },
    { name: "Shreekhand (Maharashtrian-Sweet)", category: "Maharashtrian-Sweet", file: "./IN/MAHARASTRIAN/shreekhand.html" },
    { name: "Tambda Rassa (Maharashtrian-NonVeg)", category: "Maharashtrian-NonVeg", file: "./IN/MAHARASTRIAN/tambda-rassa.html" },
    { name: "Thalipeeth (Maharashtrian-Veg)", category: "Maharashtrian-Veg", file: "./IN/MAHARASTRIAN/thalipeeth.html" },
    { name: "Vada Pav (Maharashtrian-Snack)", category: "Maharashtrian-Snack", file: "./IN/MAHARASTRIAN/vada-pav.html" },
    { name: "Zunka Bhakri (Maharashtrian-Veg)", category: "Maharashtrian-Veg", file: "./IN/MAHARASTRIAN/zunka-bhakri.html" },
    // add
    // Rajasthani Recipes (Veg, Non-Veg, Sweets, Snacks, Breads, Accompaniments)
    { name: "Dal Baati Churma (Rajasthani-Veg)", category: "Rajasthani-Veg", file: "./IN/RAJASTHANI/dalbati.html" },
    { name: "Gatte ki Sabji (Rajasthani-Veg)", category: "Rajasthani-Veg", file: "./IN/RAJASTHANI/gatte.html" },
    { name: "Ker Sangri (Rajasthani-Veg)", category: "Rajasthani-Veg", file: "./IN/RAJASTHANI/kersagri.html" },
    { name: "Rajasthani Kadhi (Rajasthani-Veg)", category: "Rajasthani-Veg", file: "./IN/RAJASTHANI/kadhi.html" },
    { name: "Rajasthani Khichdi (Rajasthani-Veg)", category: "Rajasthani-Veg", file: "./IN/RAJASTHANI/khichdi.html" },
    { name: "Laal Maas (Rajasthani-NonVeg)", category: "Rajasthani-NonVeg", file: "./IN/RAJASTHANI/laal mass.html" },
    { name: "Safed Maas (Rajasthani-NonVeg)", category: "Rajasthani-NonVeg", file: "./IN/RAJASTHANI/safedmaas.html" },
    { name: "Bajre Ki Roti (Rajasthani-Bread)", category: "Rajasthani-Bread", file: "./IN/RAJASTHANI/bajre.html" },
    { name: "Makki Ki Roti (Rajasthani-Bread)", category: "Rajasthani-Bread", file: "./IN/RAJASTHANI/makki.html" },
    { name: "Missi Roti (Rajasthani-Bread)", category: "Rajasthani-Bread", file: "./IN/RAJASTHANI/missiroti.html" },
    { name: "Tandoori Roti (Rajasthani-Bread)", category: "Rajasthani-Bread", file: "./IN/RAJASTHANI/tandoor.html" },
    { name: "Pyaz Kachori (Rajasthani-Snack)", category: "Rajasthani-Snack", file: "./IN/RAJASTHANI/pyazkachori.html" },
    { name: "Mirchi Bada (Rajasthani-Snack)", category: "Rajasthani-Snack", file: "./IN/RAJASTHANI/mirchivada.html" },
    { name: "Moong Dal Pakoda (Rajasthani-Snack)", category: "Rajasthani-Snack", file: "./IN/RAJASTHANI/mongpakoda.html" },
    { name: "Bikaneri Bhujia (Rajasthani-Snack)", category: "Rajasthani-Snack", file: "./IN/RAJASTHANI/bikaneri.html" },
    { name: "Aam Panna (Rajasthani-Beverage)", category: "Rajasthani-Beverage", file: "./IN/RAJASTHANI/AamPanna.html" },
    { name: "Garlic Chutney (Rajasthani-Accompaniment)", category: "Rajasthani-Accompaniment", file: "./IN/RAJASTHANI/GarlicChutney.html" },
    { name: "Papad (Rajasthani-Accompaniment)", category: "Rajasthani-Accompaniment", file: "./IN/RAJASTHANI/Papad .html" },
    { name: "Pickles (Rajasthani-Accompaniment)", category: "Rajasthani-Accompaniment", file: "./IN/RAJASTHANI/Pickles .html" },
    { name: "Churma Laddu (Rajasthani-Sweet)", category: "Rajasthani-Sweet", file: "./IN/RAJASTHANI/churma.html" },
    { name: "Balushahi (Rajasthani-Sweet)", category: "Rajasthani-Sweet", file: "./IN/RAJASTHANI/balusahi.html" },
    { name: "Ghevar (Rajasthani-Sweet)", category: "Rajasthani-Sweet", file: "./IN/RAJASTHANI/ghevar.html" },
    { name: "Imarti (Rajasthani-Sweet)", category: "Rajasthani-Sweet", file: "./IN/RAJASTHANI/imrti.html" },
    { name: "Moong Dal Halwa (Rajasthani-Sweet)", category: "Rajasthani-Sweet", file: "./IN/RAJASTHANI/moongdal.html" },
    // south 
    { name: "Appam (South Indian)", category: "South Indian", file: "./IN/SOUTH INDIAN/appam.html" },
    { name: "Avial (South Indian)", category: "South Indian", file: "./IN/SOUTH INDIAN/avial.html" },
    { name: "Bisi Bele Bath (South Indian)", category: "South Indian", file: "./IN/SOUTH INDIAN/bisibele.html" },
    { name: "Chettinad Chicken (South Indian-NonVeg)", category: "South Indian-NonVeg", file: "./IN/SOUTH INDIAN/chetiand.html" },
    { name: "Coconut Rice (South Indian)", category: "South Indian", file: "./IN/SOUTH INDIAN/cocoutr.html" },
    { name: "Curd Rice (South Indian)", category: "South Indian", file: "./IN/SOUTH INDIAN/curdrice.html" },
    { name: "Dosa (South Indian)", category: "South Indian", file: "./IN/SOUTH INDIAN/dosa.html" },
    { name: "Egg Curry (South Indian-NonVeg)", category: "South Indian-NonVeg", file: "./IN/SOUTH INDIAN/eggcuary.html" },
    { name: "Filter Coffee (South Indian-Beverage)", category: "South Indian-Beverage", file: "./IN/SOUTH INDIAN/filtercoffe.html" },
    { name: "Fish Moilee (South Indian-NonVeg)", category: "South Indian-NonVeg", file: "./IN/SOUTH INDIAN/fishm.html" },
    { name: "Idli (South Indian)", category: "South Indian", file: "./IN/SOUTH INDIAN/idli.html" },
    { name: "Idiappam (South Indian)", category: "South Indian", file: "./IN/SOUTH INDIAN/idlipam.html" },
    { name: "Kesari Bath (South Indian-Sweet)", category: "South Indian-Sweet", file: "./IN/SOUTH INDIAN/kesri.html" },
    { name: "Kottu Roti (South Indian)", category: "South Indian", file: "./IN/SOUTH INDIAN/kottu.html" },
    { name: "Lemon Rice (South Indian)", category: "South Indian", file: "./IN/SOUTH INDIAN/lrice.html" },
    { name: "Mysore Pak (South Indian-Sweet)", category: "South Indian-Sweet", file: "./IN/SOUTH INDIAN/mysoor.html" },
    { name: "Neer Dosa (South Indian)", category: "South Indian", file: "./IN/SOUTH INDIAN/neerdosa.html" },
    { name: "Panakam (South Indian-Beverage)", category: "South Indian-Beverage", file: "./IN/SOUTH INDIAN/panakam.html" },
    { name: "Parotta (South Indian)", category: "South Indian", file: "./IN/SOUTH INDIAN/parota.html" },
    { name: "Payasam (South Indian-Sweet)", category: "South Indian-Sweet", file: "./IN/SOUTH INDIAN/payasam.html" },
    { name: "Pesarattu (South Indian)", category: "South Indian", file: "./IN/SOUTH INDIAN/Pesarattu.html" },
    { name: "Pongal (South Indian)", category: "South Indian", file: "./IN/SOUTH INDIAN/pongal.html" },
    { name: "Poriyal (South Indian)", category: "South Indian", file: "./IN/SOUTH INDIAN/poriyal.html" },
    { name: "Rasam (South Indian)", category: "South Indian", file: "./IN/SOUTH INDIAN/rasam.html" },
    { name: "Sambar (South Indian)", category: "South Indian", file: "./IN/SOUTH INDIAN/sambhar.html" },
    { name: "Tamarind Rice (Puliyodarai) (South Indian)", category: "South Indian", file: "./IN/SOUTH INDIAN/tamarind.html" },
    { name: "Theeyal (South Indian)", category: "South Indian", file: "./IN/SOUTH INDIAN/theeyal.html" },
    { name: "Unniyappam (South Indian-Sweet)", category: "South Indian-Sweet", file: "./IN/SOUTH INDIAN/uniyaapan.html" },
    { name: "Upma (South Indian)", category: "South Indian", file: "./IN/SOUTH INDIAN/upma.html" },
    { name: "Uttapam (South Indian)", category: "South Indian", file: "./IN/SOUTH INDIAN/uttapam.html" },
    { name: "Medu Vada (South Indian)", category: "South Indian", file: "./IN/SOUTH INDIAN/vada.html" },
    // more populer
    // Popular All-India Recipes (direct HTMLs in ALL POPULER RECIPY'S)
    { name: "Chicken Biryani", category: "Popular-NonVeg", file: "./ALL POPULER RECIPY'S/biryani.html" },
    { name: "Masala Dosa", category: "Popular-Veg", file: "./ALL POPULER RECIPY'S/masala dosa.html" },
    { name: "Paneer Butter Masala", category: "Popular-Veg", file: "./ALL POPULER RECIPY'S/PaneerButterMasala.html" },
    { name: "Aloo Gobi", category: "Popular-Veg", file: "./10 popular recipe/Aloo Gobi.html" },
    { name: "Chole Bhature", category: "Popular-Veg", file: "./10 popular recipe/Chole Bhature.html" },
    { name: "Dal Tadka", category: "Popular-Veg", file: "./10 popular recipe/Dal Tadka.html" },
    { name: "Gulab Jamun", category: "Popular-Sweet", file: "./10 popular recipe/Gulab Jamun.html" },
    { name: "Palak Paneer", category: "Popular-Veg", file: "./10 popular recipe/Palak Paneer.html" },
    { name: "Pav Bhaji", category: "Popular-Veg", file: "./10 popular recipe/pavbhaji.html" },
    { name: "Rajma", category: "Popular-Veg", file: "./10 popular recipe/Rajma.html" },
    { name: "Rogan Josh", category: "Popular-NonVeg", file: "./10 popular recipe/Rogan Josh.html" },
    { name: "Samosa", category: "Popular-Snack", file: "./10 popular recipe/Samosa.html" },
    { name: "Tandoori Chicken", category: "Popular-NonVeg", file: "./10 popular recipe/Tandoori Chicken.html" },
];


const searchInput = document.getElementById('search');
const suggestionsBox = document.getElementById('suggestions');

searchInput.addEventListener('input', function () {
    const query = this.value.toLowerCase();
    suggestionsBox.innerHTML = '';

    if (query.length === 0) return;

    const matches = recipes.filter(r => r.name.toLowerCase().includes(query));

    matches.forEach(match => {
        const div = document.createElement('div');
        div.textContent = match.name;
        div.addEventListener('click', (e) => {
            window.location.href = match.file;
        });
        suggestionsBox.appendChild(div);
    });
});
